# Generated by Django 4.2.1 on 2023-05-16 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios_adapta_app.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('minutos', models.IntegerField()),
                ('minuto_estabilizacion', models.IntegerField()),
                ('laeq', models.FloatField()),
                ('l10', models.FloatField()),
                ('l90', models.FloatField()),
                ('estandard', models.FloatField()),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios_adapta_app.punto')),
            ],
        ),
    ]
