# Generated by Django 4.2.1 on 2023-05-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_adapta_app', '0002_punto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='l20',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicion',
            name='l30',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicion',
            name='l40',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicion',
            name='l50',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicion',
            name='l60',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicion',
            name='l70',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicion',
            name='l80',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
