# Generated by Django 4.2.2 on 2023-06-14 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_adapta_app', '0003_medicion_l20_medicion_l30_medicion_l40_medicion_l50_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='experiencia_Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='experiencia_Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='experiencia_Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='experiencia_Localizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='experiencia_Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ficha', models.FileField(blank=True, null=True, upload_to='fichas/')),
                ('comentarios', models.TextField()),
                ('atestado_hecho', models.BooleanField()),
                ('atestado_firmado', models.BooleanField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios_adapta_app.experiencia_categoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios_adapta_app.experiencia_cliente')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios_adapta_app.experiencia_contacto')),
                ('localizaciones', models.ManyToManyField(to='servicios_adapta_app.experiencia_localizacion')),
            ],
        ),
        migrations.CreateModel(
            name='experiencia_Contrato',
            fields=[
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('sector', models.CharField(choices=[('sector1', 'Sector 1'), ('sector2', 'Sector 2'), ('sector3', 'Sector 3')], max_length=255)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios_adapta_app.experiencia_proyecto')),
            ],
        ),
    ]
