# Generated by Django 4.2.2 on 2023-06-20 22:49

from django.db import migrations, models
import django.db.models.deletion
import servicios_adapta_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_adapta_app', '0004_experiencia_categoria_experiencia_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='experienciaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField(blank=True, default=servicios_adapta_app.models.experienciaContrato.fecha_fin_default, null=True)),
                ('codigo', models.CharField(max_length=8)),
                ('catServicios', models.CharField(choices=[('categoria1', 'Categoria 1'), ('categoria2', 'Categoria 2'), ('categoria3', 'Categoria 3'), ('categoria4', 'Categoria 4'), ('categoria5', 'Categoria 5'), ('categoria6', 'Categoria 6')], max_length=50)),
                ('ficha', models.FileField(blank=True, null=True, upload_to='')),
                ('atestado', models.FileField(blank=True, null=True, upload_to='')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios_adapta_app.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='experienciaProyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('contacto_nombre', models.CharField(max_length=100)),
                ('contacto_telefono', models.CharField(max_length=20)),
                ('contacto_mail', models.EmailField(max_length=254)),
                ('sector', models.CharField(choices=[('agroindustrial', 'Agroindustrial'), ('aguapot_sanea', 'Agua potable y saneamiento'), ('ambiente', 'Ambiente'), ('comercial', 'Comercial'), ('energia', 'Energía'), ('industrial', 'Industrial'), ('infraestruct', 'Infraestructura'), ('logistica', 'Logística'), ('mineria', 'Minería'), ('puertos', 'Puertos'), ('recursosH', 'Recursos Hídricos'), ('recursosS', 'Recursos Solidos'), ('salud', 'Salud'), ('servicios', 'Servicios'), ('telecom', 'Telecomunicaciones')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='experienciaRazonSocial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='experiencia_contrato',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='experiencia_proyecto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='experiencia_proyecto',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='experiencia_proyecto',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='experiencia_proyecto',
            name='localizaciones',
        ),
        migrations.DeleteModel(
            name='experiencia_Categoria',
        ),
        migrations.DeleteModel(
            name='experiencia_Cliente',
        ),
        migrations.DeleteModel(
            name='experiencia_Contacto',
        ),
        migrations.DeleteModel(
            name='experiencia_Contrato',
        ),
        migrations.DeleteModel(
            name='experiencia_Localizacion',
        ),
        migrations.DeleteModel(
            name='experiencia_Proyecto',
        ),
        migrations.AddField(
            model_name='experienciaproyecto',
            name='razon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios_adapta_app.experienciarazonsocial'),
        ),
    ]
