# Generated by Django 4.2.2 on 2023-06-20 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_adapta_app', '0005_experienciacontrato_experienciaproyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienciacontrato',
            name='fechaFin',
            field=models.CharField(default='En Curso', max_length=25),
        ),
        migrations.AlterField(
            model_name='experienciacontrato',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios_adapta_app.experienciaproyecto'),
        ),
        migrations.AlterField(
            model_name='experienciaproyecto',
            name='contacto_mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='experienciaproyecto',
            name='contacto_telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
