# Generated by Django 4.2.2 on 2023-06-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_adapta_app', '0006_alter_experienciacontrato_fechafin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='experienciaLocalizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='experienciaproyecto',
            name='localizacion',
            field=models.ManyToManyField(related_name='proyectos', to='servicios_adapta_app.experiencialocalizaciones'),
        ),
    ]
