# Generated by Django 4.2.2 on 2023-06-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_adapta_app', '0007_experiencialocalizaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencialocalizaciones',
            name='departamento',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
