# Generated by Django 4.2.2 on 2023-07-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_adapta_app', '0008_experiencialocalizaciones_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienciacontrato',
            name='codigo',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
