# Generated by Django 4.2.3 on 2023-07-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_adapta_app', '0009_alter_experienciacontrato_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienciacontrato',
            name='atestado',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experienciacontrato',
            name='ficha',
            field=models.URLField(blank=True, null=True),
        ),
    ]
