# Generated by Django 4.2.3 on 2023-07-24 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_adapta_app', '0010_alter_experienciacontrato_atestado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='experienciaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='experienciaRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContratoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios_adapta_app.experienciacontrato')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios_adapta_app.experienciaempleado')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios_adapta_app.experienciarol')),
            ],
        ),
        migrations.AddField(
            model_name='experienciacontrato',
            name='empleados',
            field=models.ManyToManyField(through='servicios_adapta_app.ContratoEmpleado', to='servicios_adapta_app.experienciaempleado'),
        ),
    ]
