# Generated by Django 4.2.2 on 2023-07-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_adapta_app', '0011_experienciaempleado_experienciarol_contratoempleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienciacontrato',
            name='fechaFin',
            field=models.DateField(),
        ),
    ]
