# Generated by Django 4.2.2 on 2023-08-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_adapta_app', '0013_alter_experienciacontrato_fechafin'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienciacontrato',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
